version: 2.1

orbs:
  maven: circleci/maven@1.1
  
jobs:
  test:
    docker:
      - image: cimg/openjdk:13.0
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber --format pretty --format json --out ~/cucumber/tests.cucumber
          when: always
      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber

workflows:
  maven_test:
    jobs:
      - maven/test
