version: 2.1

orbs:
  maven: circleci/maven@1.1
  
jobs:
  test:
    docker:
      - image: cimg/openjdk:13.0
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
workflows:
  maven_test:
    jobs:
      - maven/test
